name: ğŸš€ Dependency Update and Vulnerability Scan

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ› ï¸ Checkout code
        uses: actions/checkout@v4

      - name: ğŸ”§ Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: ğŸ“¦ Install dependencies
        run: npm install

      - name: â¬†ï¸ Check for updates
        run: |
          npm outdated > outdated.txt || true
        continue-on-error: true

      - name: ğŸ“‘ Review Outdated Packages
        id: check_outdated
        run: |
          if [ -s outdated.txt ]; then
            echo "Outdated packages found:"
            cat outdated.txt
            exit 0
          else
            echo "No outdated packages found."
            exit 1
          fi

      - name: â¬†ï¸ Update all packages
        if: steps.check_outdated.outcome == 'success'
        run: npm update

      - name: ğŸ­ Mask Debricked credentials
        run: |
          echo "::add-mask::${{ secrets.DEBRICKED_TOKEN }}"

      - name: Install Debricked CLI
        if: steps.check_outdated.outcome == 'success'
        run: |
          curl -L https://github.com/debricked/cli/releases/latest/download/cli_linux_x86_64.tar.gz | tar -xz debricked
          sudo mv debricked /usr/local/bin/debricked

      - name: ğŸ›¡ï¸ Debricked Vulnerability Scan
        if: steps.check_outdated.outcome == 'success'
        run: |
          debricked scan -t ${{ secrets.DEBRICKED_TOKEN }} -r ${{ github.repository }} -c ${{ github.sha }}

      - name: ğŸ“ Commit changes
        if: success()
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "ğŸ“¦ chore: update npm dependencies and scan for vulnerabilities"
        continue-on-error: true

      - name: ğŸš€ Push changes
        if: success()
        run: git push
