name: ğŸš€ Automatic NPM Package Update

on:
  schedule:
    # Runs at 2:00 AM every day
    - cron: '0 2 * * *'
  workflow_dispatch: # Allows you to trigger this workflow manually

jobs:
  update-packages:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ› ï¸ Checkout code
        uses: actions/checkout@v4

      - name: ğŸ”§ Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21' # Node.js 21

      - name: ğŸ“¦ Install dependencies
        run: npm install

      - name: â¬†ï¸ Update all packages
        run: npm update

      - name: ğŸ“ Commit changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "ğŸ“¦ chore: update all npm packages"
        continue-on-error: true # In case there are no updates and commit fails

      - name: ğŸš€ Push changes
        run: |
          git push
        continue-on-error: true
